title: Biotea
author: Biotea
email: biotea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PMC Sentically Represented
github_username:  biotea

header_pages:
  - contributors.md
  - dataset.md
  - model.md
  - software.md
  - queries.md
  - prototype

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
