title: Biotea
author: Biotea
email: alexgarciac@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PMC Semantically Represented
github_username:  biotea

header_pages:
  - datasets/index.md
  - contributors.html
  - model/index.html
  - software/index.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
